version: "3.1"
services:

  redis:
    image: redis:6.0
    ports:
      - "6381:6379"
    networks:
          testing_net:
            ipv4_address: 172.28.1.5
  mysql:
      build: docker/mysql
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - 3309:3306
      environment:
        MYSQL_ROOT_PASSWORD: "TTAuR1Q6bxn"
        TZ: "Asia/Ho_Chi_Minh"
      volumes:
        - ./docker/mysql_data:/var/lib/mysql
      restart: always
      networks:
            testing_net:
                ipv4_address: 172.28.1.2

  webserver:
    image: nginx:alpine
    working_dir: /application
    volumes:
      - ./application:/application
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  php-fpm:
    build: docker/php-fpm
    working_dir: /application
    volumes:
      - ./application:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    networks:
      testing_net:
        ipv4_address: 172.28.1.4

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
